services:
  fetcher:
    build: .
    command: python fetch.py
    env_file: .env
    volumes:
      - ./fuel.db:/app/fuel.db
  web:
    build: .
    volumes:
      - ./fuel.db:/app/fuel.db

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data: